version: '3.7'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  api:
    depends_on:
      - db
    restart: unless-stopped
    build: .
    ports:
      - '3000:3000'
    expose:
      - '3000'
